-- 회원(CUSTOMER) 테이블 - 6개(aaa,bbb,ccc,ddd,eee,fff)
INSERT INTO CUSTOMER(cID, cPW, cNAME, cTEL, cEMAIL, cADDRESS, cGENDER, cBIRTH)
  VALUES('aaa','111','홍길동','010-1111-1111','hong@hong.com','서울시 서대문구','m','1999-11-11');
INSERT INTO CUSTOMER(cID, cPW, cNAME, cTEL, cEMAIL, cGENDER, cBIRTH)
  VALUES('bbb','111','2길동','010-2222-2222','인천시 남동구','m','2010-03-12');
INSERT INTO CUSTOMER(cID, cPW, cNAME)
  VALUES('ccc','111','3길동');
INSERT INTO CUSTOMER(cID, cPW, cNAME, cEMAIL, cADDRESS, cGENDER)
  VALUES('ddd','111','4길동','hong@hong.com','제주도','m');
INSERT INTO CUSTOMER(cID, cPW, cNAME, cTEL, cEMAIL, cADDRESS, cGENDER, cBIRTH)
  VALUES('eee','111','5길동','010-5555-5555','hong@hong.com','서울시 서대문구','m','1988-08-03');
INSERT INTO CUSTOMER(cID, cPW, cNAME, cTEL, cEMAIL, cADDRESS, cGENDER, cBIRTH)
  VALUES('fff','111','6길동','010-6666-6666','hong@hong.com','서울시 서대문구','m','2012-02-02');
  
SELECT * FROM CUSTOMER;
COMMIT;

-- 파일첨부게시판(FILEBOARD) 테이블 - 3개(글1, 글2, 글2-1) - 하나는 첨부파일1.docx이 있는 걸로
INSERT INTO FILEBOARD(fNUM, cID, fSUBJECT, fCONTENT, fFILENAME, fPW, fREF, fRE_STEP, fRE_LEVEL, fIP)
 VALUES(FILEBOARD_SEQ.NEXTVAL, 'aaa', '글1', '본문1', '1.docx', '111', FILEBOARD_SEQ.CURRVAL, 0, 0, '192.168.0.1'); -- 원글 글1 첨부파일 있음
INSERT INTO FILEBOARD(fNUM, cID, fSUBJECT, fCONTENT, fFILENAME, fPW, fREF, fRE_STEP, fRE_LEVEL, fIP)              
 VALUES(FILEBOARD_SEQ.NEXTVAL, 'bbb', '글2', '본문2', NULL, '111', FILEBOARD_SEQ.CURRVAL, 0, 0, '172.222.32.1');      -- 원글 글2 첨부파일 없음
INSERT INTO FILEBOARD(fNUM, cID, fSUBJECT, fCONTENT, fFILENAME, fPW, fREF, fRE_STEP, fRE_LEVEL, fIP)            
 VALUES(FILEBOARD_SEQ.NEXTVAL, 'ccc', '글2-1', '본문2-1', NULL, '111', 2, 1, 1, '245.101.26.22');                      -- 답글 글2-1 첨부파일 없음

SELECT * FROM FILEBOARD;
COMMIT;
ROLLBACK;

-- 도서(BOOK)테이블 dummy data - 15개

INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '내일의 부',16000,'100.jpg','noImg.png','좋아',10);
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '3층 서기실의 암호',20000,'101.jpg','noImg.png','태영호 증언',10);
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '당신이 글을 쓰면 좋겠습니다',14000,'102.jpg','noImg.png','좋아',5);
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '울트라러닝',16000,'103.jpg','noImg.png','좋아',5);
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '내가 왔다',11500,'104.jpg','noImg.png','좋아',10);
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '나의 서툰 위로가 너에게 닿기를',13000,'105.jpg','noImg.png','좋아',30);
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '아직 멀었다는 말',13500,'106.jpg','noImg.png','좋아',10);
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '소금 지방 산열',33000,'107.jpg','noImg.png','좋아',10);
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '디레버리징',20000,'108.jpg','noImg.png','좋아',10);
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '너와 나의 암호말',18000,'109.jpg','noImg.png','좋아',5);
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '오늘도 펭수, 내일도 펭수',17000,'110.jpg','noImg.png','좋아',10);
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '지적대화를 위한 넓고 얕은 지식2',1600,'111.jpg','noImg.png','좋아',30);
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '트렌드코리아 2020',2000,'112.jpg','noImg.png','2020 트렌드 키워드 ',15);
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '여행의 이유',1800,'113.jpg','noImg.png','김영하의 여행 경험',10);
INSERT INTO BOOK (bID, bTITLE, bPRICE, bIMAGE1, bIMAGE2, bCONTENT, bDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '작은 아씨들',2000,'114.jpg','noImg.png','좋다 ',10);

SELECT * FROM BOOK;
commit;
