-- 테이블 생성 & 더미데이터

-- 테이블 및 시퀀스 삭제
DROP TABLE PERSON;
DROP TABLE JOB;
DROP SEQUENCE PSEQ;

-- 테이블 및 시퀀스 생성
CREATE TABLE JOB(
    JNO NUMBER(2) PRIMARY KEY,
    JNAME VARCHAR2(50)
);

CREATE TABLE PERSON(
    PNO NUMBER(5) PRIMARY KEY,
    PNAME VARCHAR2(50) NOT NULL,
    JNO NUMBER(2) REFERENCES JOB(JNO) NOT NULL,
    KOR NUMBER(3),
    ENG NUMBER(3),
    MAT NUMBER(3),
    CHECK(KOR>0 AND ENG>0 AND MAT>0)
);

CREATE SEQUENCE PSEQ MAXVALUE 99999 NOCACHE NOCYCLE;

-- 더미데이터 insert (정우성, 박세영, 송혜교,..)
INSERT INTO JOB(JNO,JNAME) VALUES(10,'배우');
INSERT INTO JOB(JNO,JNAME) VALUES(20,'가수');
INSERT INTO JOB(JNO,JNAME) VALUES(30,'개그맨');

SELECT * FROM JOB;

INSERT INTO PERSON VALUES(PSEQ.NEXTVAL,'정우성',10,90,80,81);
INSERT INTO PERSON VALUES(PSEQ.NEXTVAL,'박세영',10,80,90,80);
INSERT INTO PERSON VALUES(PSEQ.NEXTVAL,'배수지',20,20,90,90);
INSERT INTO PERSON VALUES(PSEQ.NEXTVAL,'설현',20,95,95,95);
INSERT INTO PERSON VALUES(PSEQ.NEXTVAL,'송혜교',10,100,100,100);
SELECT * FROM PERSON;

COMMIT;
