-- [ V ] 그룹함수 : SUM, AVG, MIN, MAX, COUNT, STDDEV(표준편차), VARIANCE(분산)
SELECT MAX(SAL), MIN(SAL), COUNT(SAL) FROM EMP;
SELECT DEPTNO, MAX(SAL) FROM EMP GROUP BY DEPTNO;  -- 부서별
SELECT MAX(SAL) FROM EMP;  -- 최대 급여를 받는 사람의 이름과 최대급여 -> VI. 서브쿼리
SELECT ENAME, SAL FROM EMP WHERE SAL = (SELECT MAX(SAL) FROM EMP);

-- ★ 1. 그룹함수들 실습
SELECT ROUND(AVG(SAL),2) FROM EMP;
SELECT AVG(SAL), SUM(SAL)/COUNT(SAL) FROM EMP;
SELECT SUM(COMM) FROM EMP;  -- NULL이 있어도 제외하고 계산
SELECT SUM(COMM), AVG(COMM) FROM EMP;  -- 모든 그룹함수는 NULL을 제외하고 계산. 평균이 14개가 기준이 아닌 4개 기준이 되버림
SELECT COUNT(*) FROM EMP;  -- 테이블 행수



SELECT SUM(COMM), AVG(NVL(COMM,0)) FROM EMP; 