
DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;
DROP SEQUENCE MEMBER_MNO_SQ;

CREATE SEQUENCE MEMBER_MNO_SQ
    MAXVALUE 9999
    NOCACHE    
    NOCYCLE; 

CREATE TABLE MEMBER_LEVEL(
    LEVELNO   NUMBER(1) PRIMARY KEY,
    LEVELNAME VARCHAR2(30) NOT NULL
);
INSERT INTO MEMBER_LEVEL VALUES(-1,'black');
INSERT INTO MEMBER_LEVEL VALUES(0,'일반');
INSERT INTO MEMBER_LEVEL VALUES(1,'실버');
INSERT INTO MEMBER_LEVEL VALUES(2,'골드');
SELECT * FROM MEMBER_LEVEL;

CREATE TABLE MEMBER(
    mNO     NUMBER(4) PRIMARY KEY,
    mNAME   VARCHAR2(30) NOT NULL,
    mPW     VARCHAR2(30) CHECK(LENGTH(mPW) BETWEEN 1 AND 8),
    mEMAIL  VARCHAR2(50) UNIQUE,
    mPOINT  NUMBER(7,2) CHECK(mPOINT >= 0),
    mRDATE  DATE DEFAULT SYSDATE,
    LEVELNO NUMBER(1),
    FOREIGN KEY(LEVELNO) REFERENCES MEMBER_LEVEL(LEVELNO)
);
SELECT * FROM MEMBER;

INSERT INTO MEMBER VALUES (
    MEMBER_MNO_SQ.NEXTVAL,
    '홍길동',
    'aa',
    'hong@hong.com',
    0,
    TO_DATE('22/03/10','RR/MM/DD'),
    0
);

INSERT INTO MEMBER (mNO, mNAME, mPW, mEMAIL, mPOINT, mRDATE, LEVELNO)  
    VALUES (MEMBER_MNO_SQ.NEXTVAL,
            '신길동',
            'bb',
            'sin@sin.com',
            1000,
            TO_DATE('22/04/01','RR/MM/DD'),
            1
);

SELECT MNO, 
        MNAME,
        TO_CHAR(MRDATE,'YYYY-MM-DD') mRDATE,
        MEMAIL,MPOINT, 
        CONCAT(LEVELNAME,'고객') LEVELNAME 
    FROM MEMBER M,MEMBER_LEVEL L
    WHERE M.LEVELNO = L.LEVELNO;

COMMIT;

