-- drop table
DROP TABLE ORDERDETAIL;
DROP TABLE ORDERS;
DROP TABLE PRODUCTSIZE;
DROP TABLE CART;
DROP TABLE PRODUCT;
DROP TABLE NOTICE;
DROP TABLE ADMIN;
DROP TABLE FAQ;
DROP TABLE QNA;
DROP TABLE COMMENTS;
DROP TABLE REVIEW;
DROP TABLE MEMBERGRADE;
DROP TABLE MEMBER;

-- drop sequence
DROP SEQUENCE ASDF;

-- create table
CREATE TABLE MEMBER(
  memberID VARCHAR2(100) PRIMARY KEY,
  memberPW VARCHAR2(100) NOT NULL,
  memberNAME VARCHAR2(100),
  memberEMAIL VARCHAR2(500),
  memberTEL VARCHAR2(100),
  memberADDR VARCHAR2(500),
  memberBIRTH DATE,
  memberPOINT NUMBER(10)
);
CREATE TABLE MEMBERGRADE(
  GRADE VARCHAR2(100),
  lowAMOUNT NUMBER(10),
  hiAMOUNT NUMBER(10)
);
CREATE TABLE PRODUCT(
  productCODE VARCHAR2(100) PRIMARY KEY,
  CATEGORY VARCHAR2(100) NOT NULL,
  productNAME VARCHAR2(500) NOT NULL,
  productIMAGE1 VARCHAR2(500),
  productIMAGE2 VARCHAR2(500),
  productIMAGE3 VARCHAR2(500),
  contentIMAGE CLOB,
  productCONTENT VARCHAR2(4000),
  productPRICE NUMBER(10) CHECK(productPRICE > 0) NOT NULL,
  productDISCOUNT NUMBER(4,1),
  productDATE DATE DEFAULT SYSDATE NOT NULL,
  productSTOCK NUMBER(4) CHECK(productSTOCK >= 0) NOT NULL,
  productUSED VARCHAR2(1) NOT NULL
);
CREATE TABLE PRODUCTSIZE(
  productCODE VARCHAR2(100) REFERENCES PRODUCT(productCODE),
  productSIZE VARCHAR2(100),
  CONSTRAINT PSIZE_PK PRIMARY KEY(productCODE,productSIZE)
);
CREATE TABLE CART(
  cartNUM NUMBER(4) PRIMARY KEY,
  memberID VARCHAR2(100) REFERENCES MEMBER(memberID) NOT NULL,
  productCODE VARCHAR2(100) REFERENCES PRODUCT(productCODE) NOT NULL,
  productSIZE VARCHAR2(100) REFERENCES PRODUCTSIZE(productSIZE),
  QTY NUMBER(3),
  COST NUMBER(10)
);
CREATE TABLE ORDERS(
  orderNUM VARCHAR2(20) PRIMARY KEY,
  memberID VARCHAR2(100) NOT NULL REFERENCES MEMBER(memberID),
  orderDATE DATE DEFAULT SYSDATE NOT NULL,
  orderNAME VARCHAR2(100) NOT NULL,
  orderADDR VARCHAR2(500) NOT NULL,
  orderTEL VARCHAR2(100) NOT NULL
);
CREATE TABLE ORDERSDETAIL(
  ODNO NUMBER(4) PRIMARY KEY,
  orderNUM VARCHAR2(100) NOT NULL REFERENCES ORDERS(orderNUM),
  productCODE VARCHAR2(100) NOT NULL REFERENCES PRODUCT(productCODE),
  productSIZE VARCHAR2(100) REFERENCES PRODUCTSIZE(productSIZE),
  QTY NUMBER(3),
  COST NUMBER(10)
);











