-- drop table
DROP TABLE MOVIE_ACTOR;
DROP TABLE ACTOR;
DROP TABLE MTAG;
DROP TABLE GOOD;
DROP TABLE RATING;
DROP TABLE RECOMMEND;
DROP TABLE COMMENTS;
DROP TABLE REVIEW;
DROP TABLE USERS;
DROP TABLE USER_GRADE;
DROP TABLE MOVIE;
DROP TABLE ADMIN;
-- drop sequence






-- create table
CREATE TABLE ADMIN(
  ADMIN_ID VARCHAR2(30) PRIMARY KEY,
  ADMIN_PW VARCHAR2(30) NOT NULL,
  ADMIN_NAME VARCHAR2(30) NOT NULL
);
CREATE TABLE MOVIE(
  MOVIE_ID VARCHAR2(100) PRIMARY KEY,
  MOVIE_NAME VARCHAR2(100) NOT NULL,
  MOVIE_SUMMARY VARCHAR2(4000),
  MOVIE_RUNNING NUMBER(5),
  MOVIE_IMAGE VARCHAR2(100) DEFAULT 'NOIMG.JPG' NOT NULL,
  MOVIE_DATE DATE,
  MOVIE_GRADE VARCHAR2(100),
  MOVIE_AUDIENCE NUMBER,
  MOVIE_STATE NUMBER(1) DEFAULT 0 NOT NULL
);
CREATE TABLE MTAG(
  TAG_ID VARCHAR2(100) PRIMARY KEY,
  MOVIE_ID VARCHAR2(100) REFERENCES MOVIE(MOVIE_ID) NOT NULL
);
CREATE TABLE ACTOR(
  ACTOR_ID VARCHAR2(100) PRIMARY KEY,
  ACTOR_NAME VARCHAR2(100) NOT NULL
);
CREATE TABLE MOVIE_ACTOR(
  MA_NO NUMBER PRIMARY KEY,
  MOVIE_ID VARCHAR2(100) REFERENCES MOVIE(MOVIE_ID) NOT NULL,
  ACTOR_ID VARCHAR2(100) REFERENCES ACTOR(ACTOR_ID) NOT NULL
);
CREATE TABLE USER_GRADE(
  GRADE_NO NUMBER(1) PRIMARY KEY,
  GRADE_NAME VARCHAR2(100) UNIQUE NOT NULL
);
CREATE TABLE USERS(
  USER_ID VARCHAR2(30) PRIMARY KEY,
  USER_PW VARCHAR2(30) NOT NULL,
  USER_NAME VARCHAR2(30) NOT NULL,
  USER_BIRTH DATE NOT NULL,
  USER_GENDER VARCHAR2(10) NOT NULL,
  USER_EMAIL VARCHAR2(100),
  USER_TELL VARCHAR2(30) UNIQUE NOT NULL,
  GRADE_NO NUMBER(1) REFERENCES USER_GRADE(GRADE_NO) NOT NULL
);
CREATE TABLE REVIEW(
  REVIEW_NO NUMBER PRIMARY KEY,
  USER_ID VARCHAR2(30) REFERENCES USERS(USER_ID) NOT NULL,
  MOVIE_ID VARCHAR2(100) REFERENCES MOVIE(MOVIE_ID) NOT NULL,
  REVIEW_TITLE VARCHAR2(100) NOT NULL,
  REVIEW_CONTENT VARCHAR2(4000) NOT NULL,
  REVIEW_HIT NUMBER DEFAULT 0 NOT NULL,
  REVIEW_DATE DATE DEFAULT SYSDATE NOT NULL,
  REVIEW_UPDATE DATE,
  REVIEW_GROUP NUMBER,
  REVIEW_STEP NUMBER,
  REVIEW_INDENT NUMBER
);
CREATE TABLE RECOMMEND(
  RECOMMEND_NO NUMBER PRIMARY KEY,
  REVIEW_NO NUMBER REFERENCES REVIEW(REVIEW_NO) NOT NULL,
  USER_ID VARCHAR2(30) REFERENCES USERS(USER_ID) NOT NULL
);
CREATE TABLE COMMENTS(
  COMMENT_NO NUMBER PRIMARY KEY,
  REVIEW_NO NUMBER REFERENCES REVIEW(REVIEW_NO) NOT NULL,
  USER_ID VARCHAR2(30) REFERENCES USERS(USER_ID) NOT NULL,
  COMMENT_CONTENT VARCHAR2(1000) NOT NULL,
  COMMENT_DATE DATE DEFAULT SYSDATE NOT NULL
);
CREATE TABLE RATING(
  RATING_NO NUMBER PRIMARY KEY,
  MOVIE_ID VARCHAR2(100) REFERENCES MOVIE(MOVIE_ID),
  .....
);
CREATE TABLE GOOD();....

-- create sequence
CREATE SEQUENCE MA_SEQ NOCACHE NOCYCLE;
CREATE SEQUENCE REVIEW_SEQ NOCACHE NOCYCLE;
CREATE SEQUENCE RECOMMEND_SEQ NOCACHE NOCYCLE;
CREATE SEQUENCE COMMENTS_SEQ NOCACHE NOCYCLE;
CREATE SEQUENCE RATING_SEQ NOCACHE NOCYCLE;
CREATE SEQUENCE GOOD_SEQ....


