-- 테이블 및 시퀀스 삭제
DROP TABLE PERSON;
DROP TABLE JOB;
DROP SEQUENCE PSEQ;

-- 테이블 및 시퀀스 생성
CREATE TABLE JOB(
    JNO NUMBER(2) PRIMARY KEY,
    JNAME VARCHAR2(50)
);

CREATE TABLE PERSON(
    PNO NUMBER(5) PRIMARY KEY,
    PNAME VARCHAR2(50) NOT NULL,
    JNO NUMBER(2) REFERENCES JOB(JNO) NOT NULL,
    KOR NUMBER(3),
    ENG NUMBER(3),
    MAT NUMBER(3),
    CHECK(KOR>0 AND ENG>0 AND MAT>0)
);

CREATE SEQUENCE PSEQ
    MAXVALUE 99999
    NOCACHE
    NOCYCLE;

-- 더미데이터 insert (정우성, 박세영, 송혜교,..)
INSERT INTO JOB(JNO,JNAME) VALUES(10,'배우');
INSERT INTO JOB(JNO,JNAME) VALUES(20,'가수');
INSERT INTO JOB(JNO,JNAME) VALUES(30,'개그맨');

SELECT * FROM JOB;

INSERT INTO PERSON VALUES(PSEQ.NEXTVAL,'정우성',10,90,80,81);
INSERT INTO PERSON VALUES(PSEQ.NEXTVAL,'박세영',10,80,90,80);
INSERT INTO PERSON VALUES(PSEQ.NEXTVAL,'배수지',20,20,90,90);
INSERT INTO PERSON VALUES(PSEQ.NEXTVAL,'설현',20,95,95,95);
INSERT INTO PERSON VALUES(PSEQ.NEXTVAL,'송혜교',10,100,100,100);
SELECT * FROM PERSON;


-- 기능별 query 작성 (1, 2, 3)
-- 1 직업명 목록 출력, 받아온 입력값 INSERT
SELECT JNAME FROM JOB;

INSERT INTO PERSON VALUES(PSEQ.NEXTVAL,'이름',(SELECT JNO FROM JOB WHERE JNAME = '배우'),99,99,99);

-- 2 원하는 직업명 입력받아, 직업별 조회후 총점 추가하여 총점이 높은 순으로 이름(번호)로 출력

SELECT ROWNUM || '등' RN, A.* 
    FROM (SELECT PNAME || '(' || PNO || '번)' PNAME, JNAME, KOR, ENG, MAT, KOR+ENG+MAT TOT
        FROM PERSON P, JOB J WHERE P.JNO = J.JNO  AND P.JNO = (SELECT JNO FROM JOB WHERE JNAME = '배우')
        ORDER BY TOT DESC) A;

-- 3 

SELECT ROWNUM || '등' RN, A.* 
    FROM (SELECT PNAME || '(' || PNO || '번)' PNAME, JNAME, KOR, ENG, MAT, KOR+ENG+MAT TOT
        FROM PERSON P, JOB J WHERE P.JNO = J.JNO
        ORDER BY TOT DESC) A;




