-- drop table
DROP TABLE COMMENTS;
DROP TABLE BOARD;
DROP TABLE RATING;
DROP TABLE USERS;
DROP TABLE MOVIE_PERSON;
DROP TABLE PERSON;
DROP TABLE TAG;
DROP TABLE MOVIE;
DROP TABLE STATE;
DROP TABLE ADMIN;
-- drop sequence
DROP SEQUENCE COMMENTS_SEQ;
DROP SEQUENCE BOARD_SEQ;
DROP SEQUENCE PERSON_SEQ;
DROP SEQUENCE MOVIE_SEQ;
-- create table
CREATE TABLE ADMIN(
  adminID VARCHAR2(30) PRIMARY KEY,
  adminPW VARCHAR2(30) NOT NULL,
  adminNAME VARCHAR2(30) NOT NULL
);
CREATE TABLE STATE(
  STATE NUMBER(1) PRIMARY KEY,
  SITUATION VARCHAR2(30) NOT NULL
);
CREATE TABLE MOVIE(
  movieID VARCHAR2(100) PRIMARY KEY,
  movieNAME VARCHAR2(100) NOT NULL,
  movieSUMMARY VARCHAR2(4000),
  movieRUNNING NUMBER(5),
  movieIMAGE VARCHAR2(100) DEFAULT 'NOIMG.JPG' NOT NULL,
  movieDATE DATE,
  movieGRADE VARCHAR2(100),
  movieAUDIENCE NUMBER,
  STATE NUMBER(1) REFERENCES STATE(STATE) NOT NULL
);
CREATE TABLE TAG(
  movieID VARCHAR2(100) REFERENCES MOVIE(movieID),
  TAG VARCHAR2(30),
  CONSTRAINT TAG_PK PRIMARY KEY(movieID,TAG)
);
CREATE TABLE PERSON(
  personID VARCHAR2(100) PRIMARY KEY,
  personJOB VARCHAR2(100) NOT NULL,
  personNAME VARCHAR2(30) NOT NULL,
  personIMAGE VARCHAR2(100) DEFAULT 'nothing.png' NOT NULL,
  personGENDER VARCHAR2(10),
  personNATION VARCHAR2(100),
  personBIRTH DATE,
  personDETAIL VARCHAR2(4000)
);
CREATE TABLE MOVIE_PERSON(
  movieID VARCHAR2(100),
  personID VARCHAR2(100),
  FOREIGN KEY(movieID) REFERENCES MOVIE(movieID),
  FOREIGN KEY(personID) REFERENCES PERSON(personID),
  CONSTRAINT MOVIE_PERSON_PK PRIMARY KEY(movieID,personID)
);
CREATE TABLE USERS(
  userID VARCHAR2(30) PRIMARY KEY,
  userPW VARCHAR2(30) NOT NULL,
  userNAME VARCHAR2(30) NOT NULL,
  userBIRTH DATE NOT NULL,
  userGENDER VARCHAR2(10) NOT NULL,
  userEMAIL VARCHAR2(100),
  userTEL VARCHAR2(30) NOT NULL,
  userDATE DATE DEFAULT SYSDATE NOT NULL,
  userLIMIT DATE
);
CREATE TABLE RATING(
  userID VARCHAR2(30),
  movieID VARCHAR2(100),
  ratingCONTENT VARCHAR2(4000),
  ratingSCORE NUMBER(2) CHECK(ratingSCORE>=0 AND ratingSCORE<=10) NOT NULL,
  ratingDATE DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT RATING_userID_FK
    FOREIGN KEY(userID)
    REFERENCES USERS(userID)
    ON DELETE CASCADE,
  FOREIGN KEY(movieID) REFERENCES MOVIE(movieID),
  CONSTRAINT RATING_PK PRIMARY KEY(userID,movieID)
);
CREATE TABLE BOARD(
  boardNO NUMBER PRIMARY KEY,
  userID VARCHAR2(30) NOT NULL,
  boardTITLE VARCHAR2(100) NOT NULL,
  boardCONTENT VARCHAR2(4000) NOT NULL,
  boardHIT NUMBER DEFAULT 0 NOT NULL,
  boardDATE DATE DEFAULT SYSDATE NOT NULL,
  boardUPDATE DATE,
  boardGROUP NUMBER NOT NULL,
  boardSTEP NUMBER NOT NULL,
  boardINDENT NUMBER NOT NULL,
  boardIP VARCHAR2(30),
  CONSTRAINT BOARD_userID_FK
    FOREIGN KEY(userID)
    REFERENCES USERS(userID)
    ON DELETE CASCADE
);
CREATE TABLE COMMENTS(
  commentNO NUMBER PRIMARY KEY,
  boardNO NUMBER NOT NULL,
  userID VARCHAR2(30) NOT NULL,
  commentCONTENT VARCHAR2(1000) NOT NULL,
  commentDATE DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT COMMENTS_boardNO_FK
    FOREIGN KEY(boardNO)
    REFERENCES BOARD(boardNO)
    ON DELETE CASCADE,
  CONSTRAINT COMMENTS_userID_FK
    FOREIGN KEY(userID)
    REFERENCES USERS(userID)
    ON DELETE CASCADE
);
-- create sequence
CREATE SEQUENCE MOVIE_SEQ NOCACHE NOCYCLE;
CREATE SEQUENCE PERSON_SEQ NOCACHE NOCYCLE;
CREATE SEQUENCE BOARD_SEQ NOCACHE NOCYCLE;
CREATE SEQUENCE COMMENTS_SEQ NOCACHE NOCYCLE;

