-- drop table
DROP TABLE COMMENTS;
DROP TABLE BOARD;
DROP TABLE RATING;
DROP TABLE USERS;
DROP TABLE MOVIE_PERSON;
DROP TABLE PERSON;
DROP TABLE MOVIE_TAG;
DROP TABLE TAG;
DROP TABLE MOVIE;
DROP TABLE STATE;
DROP TABLE ADMIN;
-- drop sequence
DROP SEQUENCE COMMENTS_SEQ;
DROP SEQUENCE BOARD_SEQ;
DROP SEQUENCE PERSON_SEQ;
DROP SEQUENCE MOVIE_SEQ;
-- create table
CREATE TABLE ADMIN(
  ADMIN_ID VARCHAR2(30) PRIMARY KEY,
  ADMIN_PW VARCHAR2(30) NOT NULL,
  ADMIN_NAME VARCHAR2(30) NOT NULL
);
CREATE TABLE STATE(
  STATE NUMBER(1) PRIMARY KEY,
  SITUATION VARCHAR2(30) NOT NULL
);
CREATE TABLE MOVIE(
  MOVIE_ID VARCHAR2(100) PRIMARY KEY,
  MOVIE_NAME VARCHAR2(100) NOT NULL,
  MOVIE_SUMMARY VARCHAR2(4000),
  MOVIE_RUNNING NUMBER(5),
  MOVIE_IMAGE VARCHAR2(100) DEFAULT 'NOIMG.JPG' NOT NULL,
  MOVIE_DATE DATE,
  MOVIE_GRADE VARCHAR2(100),
  MOVIE_AUDIENCE NUMBER,
  STATE NUMBER(1) REFERENCES STATE(STATE) NOT NULL
);
CREATE TABLE TAG(
  MOVIE_ID VARCHAR2(100) REFERENCES MOVIE(MOVIE_ID),
  TAG VARCHAR2(30),
  CONSTRAINT TAG_PK PRIMARY KEY(MOVIE_ID,TAG)
);
CREATE TABLE PERSON(
  PERSON_ID VARCHAR2(100) PRIMARY KEY,
  PERSON_JOB VARCHAR2(100) NOT NULL,
  PERSON_NAME VARCHAR2(30) NOT NULL,
  PERSON_GENDER VARCHAR2(10),
  PERSON_NATION VARCHAR2(100),
  PERSON_BIRTH DATE
);
CREATE TABLE MOVIE_PERSON(
  MOVIE_ID VARCHAR2(100),
  PERSON_ID VARCHAR2(100),
  FOREIGN KEY(MOVIE_ID) REFERENCES MOVIE(MOVIE_ID),
  FOREIGN KEY(PERSON_ID) REFERENCES PERSON(PERSON_ID),
  CONSTRAINT MOVIE_PERSON_PK PRIMARY KEY(MOVIE_ID,PERSON_ID)
);
CREATE TABLE USERS(
  USER_ID VARCHAR2(30) PRIMARY KEY,
  USER_PW VARCHAR2(30) NOT NULL,
  USER_NAME VARCHAR2(30) NOT NULL,
  USER_BIRTH DATE NOT NULL,
  USER_GENDER VARCHAR2(10) NOT NULL,
  USER_EMAIL VARCHAR2(100),
  USER_TELL VARCHAR2(30) UNIQUE NOT NULL
);
CREATE TABLE RATING(
  USER_ID VARCHAR2(30),
  MOVIE_ID VARCHAR2(100),
  RATING_CONTENT VARCHAR2(4000),
  RATING_SCORE NUMBER(2) CHECK(RATING_SCORE>=0 AND RATING_SCORE<=10) NOT NULL,
  RATING_DATE DATE DEFAULT SYSDATE NOT NULL,
  FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID),
  FOREIGN KEY(MOVIE_ID) REFERENCES MOVIE(MOVIE_ID),
  CONSTRAINT RATING_PK PRIMARY KEY(USER_ID,MOVIE_ID)
);
CREATE TABLE BOARD(
  BOARD_NO NUMBER PRIMARY KEY,
  USER_ID VARCHAR2(30) REFERENCES USERS(USER_ID) NOT NULL,
  BOARD_TITLE VARCHAR2(100) NOT NULL,
  BOARD_CONTENT VARCHAR2(4000) NOT NULL,
  BOARD_HIT NUMBER DEFAULT 0 NOT NULL,
  BOARD_DATE DATE DEFAULT SYSDATE NOT NULL,
  BOARD_UPDATE DATE,
  BOARD_GROUP NUMBER NOT NULL,
  BOARD_STEP NUMBER NOT NULL,
  BOARD_INDENT NUMBER NOT NULL,
  BOARD_IP VARCHAR2(30)
);
CREATE TABLE COMMENTS(
  COMMENT_NO NUMBER PRIMARY KEY,
  BOARD_NO NUMBER REFERENCES BOARD(BOARD_NO) NOT NULL,
  USER_ID VARCHAR2(30) REFERENCES USERS(USER_ID) NOT NULL,
  COMMENT_CONTENT VARCHAR2(1000) NOT NULL,
  COMMENT_DATE DATE DEFAULT SYSDATE NOT NULL
);
-- create sequence
CREATE SEQUENCE MOVIE_SEQ NOCACHE NOCYCLE;
CREATE SEQUENCE PERSON_SEQ NOCACHE NOCYCLE;
CREATE SEQUENCE BOARD_SEQ NOCACHE NOCYCLE;
CREATE SEQUENCE COMMENTS_SEQ NOCACHE NOCYCLE;

