-- 테이블 시퀀스 삭제
DROP TABLE CUSTOMER;
DROP TABLE GRADE;
DROP SEQUENCE CUSTOMER_CID_SEQ;

-- 테이블 시퀀스 생성

CREATE TABLE GRADE(
    GNO NUMBER(1),
    GRADE VARCHAR2(30),
    LAMOUNT NUMBER(8),
    HIAMOUNT NUMBER(8),
    PRIMARY KEY(GNO)
);
SELECT * FROM GRADE;

CREATE TABLE CUSTOMER(
    CID NUMBER(7),
    CTEL VARCHAR2(30) UNIQUE,
    CNAME VARCHAR2(30),
    CPOINT NUMBER(8) DEFAULT 1000,
    CAMOUNT NUMBER(8) DEFAULT 0,
    GNO NUMBER(1) DEFAULT 1 NOT NULL,
    PRIMARY KEY(CID),
    FOREIGN KEY(GNO) REFERENCES GRADE(GNO)
);
SELECT * FROM CUSTOMER;

CREATE SEQUENCE CUSTOMER_CID_SEQ MAXVALUE 9999999 NOCACHE NOCYCLE;

-- 더미데이터 입력
INSERT INTO GRADE VALUES(1,'NORMAL',0,99999);
INSERT INTO GRADE VALUES(2,'BRONZE',100000,499999);
INSERT INTO GRADE VALUES(3,'SILVER',500000,999999);
INSERT INTO GRADE VALUES(4,'GOLD',1000000,2999999);
INSERT INTO GRADE VALUES(5,'VIP',3000000,99999999);
SELECT * FROM GRADE;

INSERT INTO CUSTOMER(CID,CTEL,CNAME) VALUES(CUSTOMER_CID_SEQ.NEXTVAL,'010-9999-9999','홍길동');
INSERT INTO CUSTOMER VALUES(CUSTOMER_CID_SEQ.NEXTVAL,'010-8888-9999','뉴진스',1000,200000,2);
INSERT INTO CUSTOMER VALUES(CUSTOMER_CID_SEQ.NEXTVAL,'010-7777-7777','아이브',1000,600000,3);
INSERT INTO CUSTOMER VALUES(CUSTOMER_CID_SEQ.NEXTVAL,'010-6666-6666','에스파',1000,1600000,4);
INSERT INTO CUSTOMER VALUES(CUSTOMER_CID_SEQ.NEXTVAL,'010-5555-5555','ITZY',1000,5600000,5);

SELECT * FROM CUSTOMER;

COMMIT;
-- JOIN
SELECT CID,CTEL,CNAME,CPOINT,CAMOUNT,C.GNO,GRADE,LAMOUNT,HIAMOUNT FROM CUSTOMER C, GRADE G   
    WHERE C.GNO = G.GNO;



--2번기능 VIP 레벨업0원 예제 
SELECT CNAME, HIAMOUNT+1 - CAMOUNT 
    FROM CUSTOMER C,GRADE G
    WHERE C.GNO = G.GNO
    AND GNO != 5;

SELECT CNAME, CAMOUNT,(SELECT HIAMOUNT+1 - CAMOUNT FROM CUSTOMER WHERE GNO!=5 AND CID=C.CID)
    FROM CUSTOMER C, GRADE G
    WHERE C.GNO = G.GNO; 


--3번기능 물품구입 레벨업예제
SELECT CNAME,CAMOUNT,C.GNO 현레벨, G.GNO 바뀔레벨,LAMOUNT,HIAMOUNT
    FROM CUSTOMER C, GRADE G;
    
SELECT CNAME, CAMOUNT, C.GNO 현레벨, G.GNO 바뀔레벨
    FROM CUSTOMER C, GRADE G
    WHERE CAMOUNT BETWEEN LAMOUNT AND HIAMOUNT;







